Add RateLimit. (60sec)
foo87b/CCWallet pull request #4
Opened 2018-05-12 16:49 UTC by serisia

# what?

I added RateLimit. (60sec)

# why?

Discord is limiting post over api.
If some users use bot constantly, others can't use normally.

2018-05-12 18:54 UTC, foo87b requested changes
If there is the same time, an ArgumentException will be thrown.

2018-05-12 18:54 UTC, foo87b commented on DiscordBot/Services/CommandHandlingService.cs
> +                        RecentUsers.Add(DateTime.Now.Ticks, arg.Author.Id);
If there is the same time, an ArgumentException will be thrown.
Because the OnMessageReceived method is async, it can be executed at the same time.

2018-05-12 22:00 UTC, serisia commented
I fixed it.
Sorry, please check code again!

2018-05-13 07:39 UTC, foo87b approved these changes

2018-05-13 07:41 UTC, foo87b commented
LGTM 👍 
Thank you very much.

2018-05-13 07:41 UTC, merged